BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE UPDATE_DOWNSTREAMS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE UPDATE_DOWNSTREAMS (
  REF_ID_V   VARCHAR2(200),
  REQ_DATE   DATE,
  ACTION_V   VARCHAR2(100),
  STATUS_V   VARCHAR2(1)
);

-- sample data: some rejected in the last hour, some older, some queued
INSERT INTO UPDATE_DOWNSTREAMS VALUES ('REF-001', SYSDATE - (10/1440), 'CREATE', 'R'); -- 10 minutes ago
INSERT INTO UPDATE_DOWNSTREAMS VALUES ('REF-002', SYSDATE - (30/1440), 'UPDATE', 'R'); -- 30 minutes ago
INSERT INTO UPDATE_DOWNSTREAMS VALUES ('REF-003', SYSDATE - (90/1440), 'DELETE', 'R'); -- 90 minutes ago (should NOT be picked)
INSERT INTO UPDATE_DOWNSTREAMS VALUES ('REF-004', SYSDATE - (5/1440),  'CREATE', 'Q'); -- already queued
COMMIT;

SELECT STATUS_V, COUNT(*) cnt
FROM UPDATE_DOWNSTREAMS
GROUP BY STATUS_V
ORDER BY STATUS_V;
